dynamic-page/cart
CoffeeShopTeam/CoffeeShopRepo pull request #105
Opened 2023-06-30 19:54 UTC by Etaizil

This is the logic for the cart. There might be changes to other code files due to merges and conflicts solving, but it should be in accordance to the last changes in dev. I will work on the style next, but at least we will have a flow.

2023-06-30 21:17 UTC, roeezach commented on backend/views/Cart/Cart.js
> +      <hr class="mb-3">
this hr causing the screen to look weired when removing an item. try to remove several items from the cart and you will see some duplicated horizional lines

2023-06-30 21:18 UTC, roeezach requested changes
it looks really good and the mean functionality work.
we still have an enoying bug:
when removing one item from the cart and then we try to edit the quantity of the other it increased the value by two or decrease by two.
lets discusses this further and try to resolve it

2023-06-30 21:18 UTC, Etaizil commented on backend/views/Cart/Cart.js
> +      <hr class="mb-3">
correct, i just moved it up into the div :) will push soon

2023-06-30 23:06 UTC, Etaizil commented on backend/views/Cart/Cart.js
> +      <hr class="mb-3">
hr removed. product-container border instead.

2023-07-01 06:31 UTC, roeezach approved these changes

2023-07-01 06:32 UTC, merged