added Twitter API and option to tweet
CoffeeShopTeam/CoffeeShopRepo pull request #50
Opened 2023-06-24 12:04 UTC by Barara98

2023-06-24 18:22 UTC, GilHeller requested changes

2023-06-24 18:22 UTC, GilHeller commented on backend/services/twitterAPI/index.js
What is this file? is this a test file?

2023-06-24 18:22 UTC, GilHeller commented on backend/services/twitterAPI/twitterClient.js
> +  appKey: process.env.API_KEY,
Change the names of the env variables to more meaningful names, since we have several api keys in our project. (like, TWITTER_API_KEY)
Do it to the other variables as well.

2023-06-26 08:25 UTC, GilHeller commented on backend/services/twitterAPI/index.js
> +const tweet = async () => {
Move this function to twitterClient.js

2023-06-26 08:49 UTC, Barara98 commented on backend/services/twitterAPI/index.js
> +const tweet = async () => {
!

2023-06-26 08:50 UTC, roeezach approved these changes

2023-06-26 08:51 UTC, merged