db-schema/Products
CoffeeShopTeam/CoffeeShopRepo pull request #51
Opened 2023-06-24 13:18 UTC by Kfirho

added schema for products.

2023-06-24 18:26 UTC, GilHeller requested changes
Great job! 
See my comments

2023-06-24 18:26 UTC, GilHeller commented on package.json
remove this file

2023-06-24 18:26 UTC, GilHeller commented on backend/models/products/product.schema.js
> +  },
Consider to add a `supplier id`. This way we could select all product of a specific supplier. (The value should be the user _id)

2023-06-24 18:44 UTC, Kfirho commented on backend/models/products/product.schema.js
> +  },
Done :)

2023-06-24 18:46 UTC, Kfirho commented on package.json
Removed it :)

2023-06-25 07:25 UTC, roeezach commented on backend/models/products/product.schema.js
> +      return id.length == 9;
if it's a user id I think it is not a good validation - it will not allow us to save users.
it is not neccesery 9 digit number.
for example, I used Gil script to create a user and this is the ID it populated for me:
`649763d15fb623c04a94f045`

see the example in my compass:
![image](https://github.com/CoffeeShopTeam/CoffeeShopRepo/assets/106396740/5457477c-53a2-4cef-a047-58e96ee8c40c)

try to use a `.test.js` file to test the code in the same manner Gil showed it will help make sure the data is saved correctly

2023-06-25 11:16 UTC, roeezach commented on backend/models/products/product.schema.js
> +    message: "id must have 9 digits",
consider adding product quantity so we can manage how much products are in stock.

2023-06-25 22:00 UTC, Kfirho commented on backend/models/products/product.schema.js
> +      return id.length == 9;
Added a validator file and changed it :)

2023-06-25 22:00 UTC, Kfirho commented on backend/models/products/product.schema.js
> +    message: "id must have 9 digits",
done :)

2023-06-26 08:11 UTC, GilHeller commented on package.json
> +{}
remove this file

2023-06-26 08:14 UTC, Kfirho commented on package.json
> +{}
removed :)

2023-06-26 08:14 UTC, merged